setxkbmap -option ctrl:nocaps

export PATH=/usr/local/cuda-8.0/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda8.0/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
export CAFFE_ROOT=/home/roy/caffe/
export PYTHONPATH=/home/roy/caffe/python:$PYTHONPATH
